packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  html-to-pdf@*:
    dependencies:
      cookie: "*"
      tslib: "*"
  ws@*:
    dependencies:
      bufferutil: "*"
      utf-8-validate: "*"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
