name: Quality check

on: push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      TAG: html-to-pdf
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint --max-warnings 0
      - name: Build container
        run: docker build --file deploy/test/Dockerfile --tag ${TAG} .
      - name: Run test in a container
        run: docker run --rm ${TAG} yarn test

  build:
#    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: muehlemannpopp/html-to-pdf
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          file: deploy/prod/Dockerfile
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
