name: Quality check

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      TAG: html-to-pdf
      PUPPETEER_SKIP_DOWNLOAD: 1
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
      - name: Build container
        run: docker build --file deploy/Dockerfile --target test --tag ${TAG} .
      - name: Run lint in a container
        run: docker run --rm ${TAG} yarn lint --max-warnings 0
      - name: Run test in a container
        run: docker run --rm ${TAG} yarn test
