name: Lint

on: ['push', 'pull_request']

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - uses: actions/checkout@v2
      - run: time yarn install
      - run: time yarn lint --max-warnings 0
