name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - uses: actions/checkout@v2
      - uses: martijnhols/actions-cache/restore@main
        id: cache
        with:
          key: yarn-cache
          path: ~/.yarn/cache
      - run: yarn install
      - run: yarn lint --max-warnings 0
      - name: Save caches back
        uses: martijnhols/actions-cache/save@main
        with:
          path: ~/.yarn/cache
          key: ${{ steps.cache.outputs.primary-key }}

  test:
    runs-on: ubuntu-latest
    env:
      TAG: html-to-pdf
    steps:
      - uses: actions/checkout@v2
      - uses: martijnhols/actions-cache/restore@main
        with:
          key: yarn-cache
          path: ~/.yarn/cache
      - name: Build container
        run: docker build --file deploy/test/Dockerfile --tag ${TAG} .
      - name: Run test in a conteiner
        run: docker run --rm ${TAG} yarn test
